### ISSUE TITLE
Liquid error: An item with the same key has already been added. Key: get_type

### ISSUE THREAD

**Issue by Jennal** [dotliquid/dotliquid#479]
### Dotliquid version
2.2.614

### Expected behavior

Code looks like this:
```csharp
var template = Template.Parse(CLASS_TEMPLETE_FULL);
var hash = Hash.FromAnonymousObject(new { data = tplData });
var content = template.Render(hash);
```

Hash is correct
![image](https://user-images.githubusercontent.com/451971/164369574-902fa969-69de-470c-8489-e5b231d17af7.png)

Data structure:
```csharp
[LiquidType("*")]
public class TemplateField
{
    public string type { get; set; }
    public string name { get; set; }
    public string desc { get; set; }
    public bool isArray { get; set; }
}

[LiquidType("*")]
public class TemplateData
{
    public string excelFile { get; set; }
    public string tableName { get; set; }
    public string tableDesc { get; set; }
    public string entityName { get; set; }
    
    public List<string> namespaces { get; set; }
    public List<TemplateField> fields { get; set; }
}
```

Template:
```liquid
// Code generated by Excel2Unity. DO NOT EDIT.
// source file: {{data.excel_file}}
// source sheet: {{data.table_name}}

{% for ns in data.namespaces -%}
using {{ns}};
{% endfor -%}

namespace Config
{
        /// <summary>
	/// {{data.entity_name}}
        ///
	/// {{data.table_desc}}
	/// </summary>
	[Serializable]
	public partial struct {{data.entity_name}}
	{
		{% for field in data.fields -%}
		/// <summary>
		/// {{field.desc}}
		/// </summary>
		public {{field.type}} {{field.name}};

		{% endfor -%}
        }
}
```

### Actual behavior

But output error:
```csharp
System.ArgumentException: An item with the same key has already been added. Key: get_type
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at DotLiquid.TypeResolution.GetMemberDictionary[T](IEnumerable`1 members, Func`2 filterMemberCallback)
   at DotLiquid.TypeResolution..ctor(Type type, Func`2 filterMemberCallback)
   at DotLiquid.DropProxy.CreateTypeResolution(Type type)
   at DotLiquid.DropBase.get_TypeResolution()
   at DotLiquid.DropBase.InvokeDrop(Object name)
   at DotLiquid.DropBase.get_Item(Object method)
   at DotLiquid.Context.TryEvaluateHashOrArrayLikeObject(Object obj, Object key, Object& value)
   at DotLiquid.Context.TryGetVariable(IEnumerator`1 partsEnumerator, Object& variable)
   at DotLiquid.Context.Variable(String markup, Boolean notifyNotFound)
   at DotLiquid.Context.Resolve(String key, Boolean notifyNotFound)
   at DotLiquid.Context.get_Item(String key, Boolean notifyNotFound)
   at DotLiquid.Variable.RenderInternal(Context context)
   at DotLiquid.Variable.Render(Context context, TextWriter result)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
```

**Comment by Jennal** [comment]
I found that `type` is a screct key word, so when I change my `type` into `type_name`. All works.

**Comment by microalps** [comment]
Issue is that LiquidType with an asterisk whitelists GetType() method which every object has. This, in Ruby naming convention, is named get_type - which incidentally conflicts with getter naming syntax. I presume the same would be for GetHashCode / HashCode property
