### ISSUE TITLE
Inconsistent rendering of arrays when done directly vs in a Sort filter

### ISSUE THREAD

**Issue by sweeeneey** [dotliquid/dotliquid#533]
### Dotliquid version
2.2.692

### Expected behavior
Given a JSON document similar to the following:

```
{
    "People":
    [
        {
            "Names":
            [
                "Joe",
                "Smith"
            ]
        },
        {
            "Names":
            [
                "Aaron",
                "Aaronsen"
            ]
        }
    ]
}
```

Rendering the following template against that document:

```
{% for person in People %}
	{{ person.Names }}
{% endfor %}
```

Produces the output:

```
JoeSmith
AaronAaronsen
```

Since {{ person.Names }} can be rendered I would expect that Names could be used as a sort filter:

```
{% assign sortedPeople = People | sort: "Names" %}
{% for person in sortedPeople %}
	{{ person.Names }}
{% endfor %}
```
 
I would expect rendering the above template would output:

```
AaronAaronsen
JoeSmith
```

### Actual behavior

When attempting to sort by an array of strings, the following exception is returned by the Render method:

{System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.ArgumentException: Object must be of type String.
   at System.String.CompareTo(Object value)
   at System.StringComparer.Compare(Object x, Object y)
   at DotLiquid.StandardFilters.<>c__DisplayClass25_0.<SortInternal>b__1(Object a, Object b)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(Span`1 keys, Comparison`1 comparer, Int32 i, Int32 j)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at DotLiquid.StandardFilters.SortInternal(StringComparer stringComparer, Object input, String property)
   at DotLiquid.StandardFilters.Sort(Context context, Object input, String property)
--- End of stack trace from previous location ---
   at DotLiquid.Strainer.Invoke(String method, List`1 args)
   at DotLiquid.Context.Invoke(String method, List`1 args)
   at DotLiquid.Variable.RenderInternal(Context context)
   at DotLiquid.Variable.Render(Context context)
   at DotLiquid.Tags.Assign.Render(Context context, TextWriter result)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)}

### Steps to reproduce the Problem (you can add files)

Render the example template provided above using the example JSON doc provided above.

**Comment by sweeeneey** [comment]
Not sure if this matches the Ruby behavior or not. Was just expecting that the properties would be resolved with common logic both in filters and when directly outputting the property.

**Comment by microalps** [comment]
Was going to say - has this been tested with Liquid itself @sweeeneey ? You can use replit to create a test case and add a link here if it matches the expected behavior. It would certainly change the priorities if Liquid itself works that way.

**Comment by sweeeneey** [comment]
@microalps, here is a replit testing the ruby liquid behavior: https://replit.com/@sweeeneey/RubyLiquidStringArraySort?v=1

Looks like Ruby's behavior does match the expected behavior. Not the current DotLiquid behavior. I also checked LiquidJS in a playground and that looks like it also matches Ruby's behavior.

**Comment by sweeeneey** [comment]
@microalps Any thoughts or updates on this one?

**Comment by microalps** [comment]
I have not been active for the last bit. I am looking now, will provide an update this weekend hopefully.

**Comment by microalps** [comment]
Reviewing the source code of ruby, it uses the "Spaceship Operator" for comparison. I read on https://ruby-for-beginners.rubymonstas.org/operators/comparison.html that arrays are comparable in Ruby. They are not comparable in .NET natively without an implemented IComparable

**Comment by microalps** [comment]
@daviburg how would you suggest handling this issue? It's a difference due to the underlying framework from my understanding. I assume this should be accepted and documented as a known difference. However, I found that the following test also fails on DotLiquid - nested sort item. Here is my ruby test - https://replit.com/@microalps/RubyLiquidNestedObjectSort#main.rb - Sort uses ResolveObjectPropertyValue which doesn't support nesting.

**Comment by sweeeneey** [comment]
@daviburg Any updates on this one? Is this a known difference? Or something that might be brought into compatibility?
