### ISSUE TITLE
Line breaks in literal strings fail to parse

### ISSUE THREAD

**Issue by mikeclayton** [dotliquid/dotliquid#541]
### Dotliquid version
[2.2.692](https://www.nuget.org/packages/DotLiquid/2.2.692)

### Expected behavior
The following template should parse:

**mytemplate.liquid**
```liquid
{% capture ATLANTIS_GH_TOKEN %}
--- begin ---
aaa
--- end ---
{% endcapture %}

{{ ATLANTIS_GH_TOKEN | replace: "
", "x" }}
```

### Actual behavior

```
MethodInvocationException: Exception calling "Parse" with "1" argument(s): "Variable '{{ ATLANTIS_GH_TOKEN | replace: "
", "x" }}' was not properly terminated with regexp: (?-mix:\}\})"
```

### Steps to reproduce the Problem (you can add files)
The following PowerShell sample fails to parse due to the literal line breaks:

```liquid
[DotLiquid.Template]::Parse(@"
{% capture ATLANTIS_GH_TOKEN %}
--- begin ---
aaa
--- end ---
{% endcapture %}
{{ ATLANTIS_GH_TOKEN | replace: "
", "x" }}
"@)

MethodInvocationException: Exception calling "Parse" with "1" argument(s): "Variable '{{ ATLANTIS_GH_TOKEN | replace: "
", "x" }}' was not properly terminated with regexp: (?-mix:\}\})"
```

whereas this one works fine without the literal line break:

```liquid
[DotLiquid.Template]::Parse(@"
{% capture ATLANTIS_GH_TOKEN %}
--- begin ---
aaa
--- end ---
{% endcapture %}
{{ ATLANTIS_GH_TOKEN | replace: "", "x" }}
"@)
```

### Additional Info

It seems that Liquid doesn't have any escape sequences for strings (e.g. "\n" for new line) so they have to be represented verbatim in strings - for line breaks this means actually putting a line break in the source code per above. Other parsers appear to support this - see:

* https://geekplayers.com/run-liquild-online.html
* https://jumpseller.co.uk/support/liquid-sandbox/

And this stackoverflow answer suggests the same thing:

* https://stackoverflow.com/questions/27694610/how-can-i-split-a-string-by-newline-in-shopify

**Comment by mikeclayton** [comment]
The stack trace from the exception is:

```
PS> $error[0].Exception

ErrorRecord                 : Exception calling "Parse" with "1" argument(s): "Variable '{{ ATLANTIS_GH_TOKEN | replace: "
                              ", "x" }}' was not properly terminated with regexp: (?-mix:\}\})"
WasThrownFromThrowStatement : False
TargetSite                  : Void ConvertToMethodInvocationException(System.Exception, System.Type, System.String, Int32,
                              System.Reflection.MemberInfo)
Message                     : Exception calling "Parse" with "1" argument(s): "Variable '{{ ATLANTIS_GH_TOKEN | replace: "
                              ", "x" }}' was not properly terminated with regexp: (?-mix:\}\})"
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo,
                              System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : DotLiquid.Exceptions.SyntaxException: Variable '{{ ATLANTIS_GH_TOKEN | replace: "
                              ", "x" }}' was not properly terminated with regexp: (?-mix:\}\})
                                 at DotLiquid.Block.CreateVariable(String token)
                                 at DotLiquid.Block.Parse(List`1 tokens)
                                 at DotLiquid.Template.ParseInternal(String source, SyntaxCompatibility syntaxCompatibilityLevel)
                                 at CallSite.Target(Closure, CallSite, Type, String)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception
                              exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                                 at CallSite.Target(Closure, CallSite, Type, String)
                                 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                                 at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

PS> $error[0].Exception.InnerException

TargetSite     : DotLiquid.Variable CreateVariable(System.String)
Message        : Variable '{{ ATLANTIS_GH_TOKEN | replace: "
                 ", "x" }}' was not properly terminated with regexp: (?-mix:\}\})
Data           : {}
InnerException :
HelpLink       :
Source         : DotLiquid
HResult        : -2146232832
StackTrace     :    at DotLiquid.Block.CreateVariable(String token)
                    at DotLiquid.Block.Parse(List`1 tokens)
                    at DotLiquid.Template.ParseInternal(String source, SyntaxCompatibility syntaxCompatibilityLevel)
                    at CallSite.Target(Closure, CallSite, Type, String)
```

**Comment by microalps** [comment]
After much research for a fix (linked) it seems best to accept as a non-supported template. I can think of the following workarounds:

- Use newline_to_br filter
- Use RegexReplace filter with finer controls for \r or \n.
- Use Capture tags to capture a new line and replace using said variable. Note that this is least recommended as it would depend on the newline used in the file itself. Your editor's newlines can be replaced silently by Git, FTP software (text vs ascii upload), etc, and have unexpected results.

As such, closing with no resolution. Feel free to reopen if the above suggestions don't get the expected results.

**Comment by microalps** [comment]
Reopening as I was able to address this issue while improving efficiency as well.
